apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ws-cfg
  namespace: workshop
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ghcr.io/niloysh/rogers-workshop:v1.0
    command: ["/bin/sh", "-c", "echo $MESSAGE && sleep $SLEEP_DURATION"]
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: ubuntu-config
          key: MESSAGE
    - name: SLEEP_DURATION
      valueFrom:
        configMapKeyRef:
          name: ubuntu-config
          key: SLEEP_DURATION
  restartPolicy: Always